- hosts: localhost
  connection: local
  vars_files:
    - default.config.yml
  roles:
    - homebrew
    - mas
    - install_dmg
  tasks:
    - name: nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
