---
# handlers file for install_dmg

- local_action: "stat path=/Applications/{{ item.app_name }}.app"
  register: app_exists

- command: mkdir -p ./tmp/
  when: app_exists.stat.exists == False

- get_url: 
    url: "{{ item.url }}" 
    dest: "./tmp/{{ item.app_name }}.dmg"
  when: app_exists.stat.exists == False

- command: "hdiutil attach ./tmp/{{ item.app_name }}.dmg -nobrowse -mountpoint ./tmp/{{ item.app_name }}"
  when: app_exists.stat.exists == False

- shell: "cp -aR ./tmp/{{ item.app_name }}/*.app /Applications/{{ item.app_name }}.app"
  when: app_exists.stat.exists == False

- command: "hdiutil detach ./tmp/{{ item.app_name }}/"
  when: app_exists.stat.exists == False

- command: rm -R ./tmp/
  when: app_exists.stat.exists == False